-------------------------------------------------------------------------------
Test set: com.itheima.controller.RedisDemoApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.494 s <<< FAILURE! - in com.itheima.controller.RedisDemoApplicationTests
contextLoads  Time elapsed: 0.837 s  <<< ERROR!
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
	at com.itheima.controller.RedisDemoApplicationTests.contextLoads(RedisDemoApplicationTests.java:16)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
	at com.itheima.controller.RedisDemoApplicationTests.contextLoads(RedisDemoApplicationTests.java:16)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused: no further information

